import 'package:flutter/material.dart';

class PeriodicTable extends StatelessWidget {
  const PeriodicTable({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.grey,
        title: Text("periodic table"),
      ),
      body: Center(
        child: SingleChildScrollView(
          child: Column(children: [
            Row(children: [
              //1
              Container(
                color: Colors.green,
                child: Center(child: Text("H")),
                height: 50,
                width: 50,
              ),
              Container(
                color: Colors.white,
                child: Center(child: Text("")),
                height: 50,
                width: 50,
              ),
              Container(
                color: Colors.white,
                child: Text(""),
                height: 50,
                width: 50,
              ),
              Container(
                color: Colors.white,
                child: Text(""),
                height: 50,
                width: 50,
              ),
              Container(
                color: Colors.white,
                child: Text(""),
                height: 50,
                width: 50,
              ),
              Container(
                color: Colors.white,
                child: Text(""),
                height: 50,
                width: 50,
              ),
              Container(
                color: Colors.white,
                child: Text(""),
                height: 50,
                width: 50,
              ),
              Container(
                color: Colors.white,
                child: Text(""),
                height: 50,
                width: 50,
              ),
              Container(
                color: Colors.white,
                height: 50,
                width: 50,
                child: Text(""),
              ),
              Container(
                color: Colors.white,
                child: Text(""),
                height: 50,
                width: 50,
              ),
              Container(
                color: Colors.white,
                child: Text(""),
                height: 50,
                width: 50,
              ),
              Container(
                color: Colors.white,
                child: Text(""),
                height: 50,
                width: 50,
              ),
              Container(
                color: Colors.white,
                child: Text(""),
                height: 50,
                width: 50,
              ),
              Container(
                color: Colors.white,
                child: Text(""),
                height: 50,
                width: 50,
              ),
              Container(
                color: Colors.white,
                child: Text(""),
                height: 50,
                width: 50,
              ),
              Container(
                color: Colors.white,
                child: Text(""),
                height: 50,
                width: 50,
              ),
              Container(
                color: Colors.white,
                height: 50,
                width: 50,
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 33, 121, 243),
                child: Center(
                  child: Text("He"),
                ),
              ),
            ]),
            Row(children: [
              //2
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 255, 232, 59),
                child: Center(child: Text("Li")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 255, 245, 59),
                child: Center(child: Text("Be")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 76, 175, 127),
                child: Center(child: Text("B")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 89, 175, 76),
                child: Center(child: Text("C")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 89, 175, 76),
                child: Center(child: Text("N")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 89, 175, 76),
                child: Center(child: Text("O")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 89, 175, 76),
                child: Center(child: Text("F")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 33, 121, 243),
                child: Center(child: Text("Ne")),
              ),
            ]),
            Row(children: [
              //3
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 255, 232, 59),
                child: Center(child: Text("Na")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 255, 245, 59),
                child: Center(child: Text("Mg")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 76, 153, 175),
                child: Center(child: Text("Al")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 76, 175, 127),
                child: Center(child: Text("Si")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 89, 175, 76),
                child: Center(child: Text("P")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 89, 175, 76),
                child: Center(child: Text("S")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 89, 175, 76),
                child: Center(child: Text("Cl")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 33, 121, 243),
                child: Center(child: Text("Ar")),
              ),
            ]),
            Row(children: [
              //4
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 255, 232, 59),
                child: Center(child: Text("K")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 255, 245, 59),
                child: Center(child: Text("Ca")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Sc")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Ti")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("V")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Cr")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Mn")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Fe")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Co")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Ni")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Cu")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Zn")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 76, 153, 175),
                child: Center(child: Text("Ga")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 76, 175, 127),
                child: Center(child: Text("Ge")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 76, 175, 127),
                child: Center(child: Text("As")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 89, 175, 76),
                child: Center(child: Text("Se")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 89, 175, 76),
                child: Center(child: Text("Br")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 96, 33, 243),
                child: Center(child: Text("Kr")),
              ),
            ]),
            Row(children: [
              //5
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 255, 232, 59),
                child: Center(child: Text("Rb")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 255, 245, 59),
                child: Center(child: Text("Sr")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Y")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Zr")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Nb")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Mo")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Tc")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Ru")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Rh")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Pd")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Ag")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Cd")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 76, 153, 175),
                child: Center(child: Text("In")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 76, 153, 175),
                child: Center(child: Text("Sn")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 76, 175, 127),
                child: Center(child: Text("Sb")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 76, 175, 127),
                child: Center(child: Text("Te")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 89, 175, 76),
                child: Center(child: Text("I")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 96, 33, 243),
                child: Center(child: Text("Xe")),
              ),
            ]),
            Row(children: [
              //6
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 255, 232, 59),
                child: Center(child: Text("Cs")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 255, 245, 59),
                child: Center(child: Text("Be")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Hf")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Ta")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("W")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Re")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Os")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Ir")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Pt")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Au")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Hg")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 76, 153, 175),
                child: Center(child: Text("Tl")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 76, 153, 175),
                child: Center(child: Text("Pb")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 76, 153, 175),
                child: Center(child: Text("Bi")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 76, 153, 175),
                child: Center(child: Text("Po")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 76, 175, 127),
                //255, 89, 175, 76),
                child: Center(child: Text("At")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 96, 33, 243),
                child: Center(child: Text("Rn")),
              ),
            ]),
            Row(children: [
              //7
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 255, 232, 59),
                child: Center(child: Text("Fr")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 255, 245, 59),
                child: Center(child: Text("Ra")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Rf")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Db")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Sg")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Bh")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Hs")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(223, 255, 255, 255),
                child: Center(child: Text("Mt")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(223, 255, 255, 255),
                child: Center(child: Text("Ds")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(223, 255, 255, 255),
                child: Center(child: Text("Rg")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.red,
                child: Center(child: Text("Cn")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(223, 255, 255, 255),
                child: Center(child: Text("Nh")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(255, 76, 153, 175),
                child: Center(child: Text("Fl")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(223, 255, 255, 255),
                child: Center(child: Text("Mc")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(223, 255, 255, 255),
                child: Center(child: Text("Lv")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(223, 255, 255, 255),
                //255, 89, 175, 76),
                child: Center(child: Text("Ts")),
              ),
              Container(
                height: 50,
                width: 50,
                color: const Color.fromARGB(223, 255, 255, 255),
                child: Center(child: Text("Og")),
              ),
            ]),
            Row(children: [
              //8
              Container(
                height: 50,
                width: 50,
                color: Colors.green,
                child: Center(child: Text("Uue")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
            ]),
            Row(children: [
              //9
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 179, 39, 87),
                child: Center(child: Text("La")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 179, 39, 87),
                child: Center(child: Text("Ce")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 179, 39, 87),
                child: Center(child: Text("Pr")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 179, 39, 87),
                child: Center(child: Text("Nd")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 179, 39, 87),
                child: Center(child: Text("Pm")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 179, 39, 87),
                child: Center(child: Text("Sm")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 179, 39, 87),
                child: Center(child: Text("Eu")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 179, 39, 87),
                child: Center(child: Text("Gd")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 179, 39, 87),
                child: Center(child: Text("Tb")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 179, 39, 87),
                child: Center(child: Text("Dy")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 179, 39, 87),
                child: Center(child: Text("Ho")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 179, 39, 87),
                child: Center(child: Text("Er")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 179, 39, 87),
                child: Center(child: Text("Tm")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 179, 39, 87),
                child: Center(child: Text("Yb")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 179, 39, 87),
                child: Center(child: Text("Lu")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
            ]),
            Row(children: [
              //10
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Colors.white,
                child: Center(child: Text("")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 176, 39, 162),
                child: Center(child: Text("Ac")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 176, 39, 162),
                child: Center(child: Text("Th")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 176, 39, 162),
                child: Center(child: Text("Pa")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 176, 39, 162),
                child: Center(child: Text("U")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 176, 39, 162),
                child: Center(child: Text("Np")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 176, 39, 162),
                child: Center(child: Text("Pu")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 176, 39, 162),
                child: Center(child: Text("Am")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 176, 39, 162),
                child: Center(child: Text("Cm")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 176, 39, 162),
                child: Center(child: Text("Bk")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 176, 39, 162),
                child: Center(child: Text("Cf")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 176, 39, 162),
                child: Center(child: Text("Es")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 176, 39, 162),
                child: Center(child: Text("Fm")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 176, 39, 162),
                child: Center(child: Text("Md")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 176, 39, 162),
                child: Center(child: Text("No")),
              ),
              Container(
                height: 50,
                width: 50,
                color: Color.fromARGB(255, 176, 39, 162),
                child: Center(child: Text("Lr")),
              ),
              Container(
                decoration: BoxDecoration(
                    color: Colors.white,
                    border: Border.all(color: Colors.white)),
                child: Text(""),
                height: 50,
                width: 50,
              ),
            ]),
            // Container(
            //   decoration: BoxDecoration(
            //    color: Colors.green, border: Border.all(color: Colors.black)),
            //   child: Text("H"),
            //   height: 50,
            //   width: 50,
            // ),
          ]),
        ),
      ),
    );
  }
}
